quarkus.application.name=auth-service
quarkus.http.port=${HTTP_PORT:8081}

# PostgreSQL - instance partagee, base unique 'jobtracker', schema dedie par service
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:jobtracker}
quarkus.datasource.password=${DB_PASSWORD:jobtracker}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/jobtracker}

quarkus.hibernate-orm.database.default-schema=auth
quarkus.hibernate-orm.database.generation=${DB_GENERATION:update}
